import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import YouTube from 'react-youtube';
import React from 'react';
import Header from '../../components/Header';
import Footer from '../../components/Footer';
import styles from '../../components/MyHome.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.body}>
      <Head>
        <title>Hitsuji Rere</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='max-w-screen-xl mx-auto'>
        <Header />

        <main>
          <div>
            <h1 className='text-3xl font-bold text-center p-6 typewriter'>
              Learn Processing
            </h1>

            <div className="text-xl w-max mx-auto">
              <div className='space-y-6 whitespace-pre-wrap'>
                <p>GitHubを用いた部内用の発展的なProcessingの学習</p>
                <p>配列，リスト，クラスについて説明</p>
                <p>
                  <Link href='https://github.com/HitsujiRere/LearnProcessing'>
                    <a className='border-b-2 hover:border-2 border-gray-100 border-b-black hover:border-black p-1 hover:p-2.5 duration-500'>GitHub</a>
                  </Link>
                </p>
              </div>
            </div>
          </div>
        </main>

        <Footer />
      </div>
    </div>
  )
}

export default Home
