import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import YouTube from 'react-youtube';
import React from 'react';
import Header from '../../components/Header';
import Footer from '../../components/Footer';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Hitsuji Rere</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='max-w-screen-xl mx-auto'>
        <Header />

        <main>
          <div>
            <h1 className='text-3xl font-bold text-center p-6 typewriter'>
              おしゃべる
            </h1>

            <div className="text-xl w-max mx-auto">
              <div className='space-y-6 whitespace-pre-wrap'>
                <p>自由な声と喋れるスマートスピーカーの追加コンテンツ</p>
                <p>DCON2021にて発表</p>
                <p>APIサーバ : Node.js</p>
                <p>合成音声作成 : Python, Tacotron2</p>
                <p>
                  <Link href='https://github.com/ishikawa-nct-iken/oshaberu_clova'>
                    <a className='border-b-2 hover:border-2 border-gray-100 border-b-black hover:border-black p-1 hover:p-2.5 duration-500'>GitHub</a>
                  </Link>
                </p>
                <YouTube
                  videoId='WpIWauBwZSs'
                  opts={{
                    playerVars: {
                      start: 2050,
                    }
                  }}
                />
                <div>
                  <Image src='/images/oshaberu/表紙.png' width={640} height={360} alt='表紙' />
                </div>
                <div>
                  <Image src='/images/oshaberu/システム構成.png' width={640} height={480} alt='システム構成' />
                </div>
                <div>
                  <Image src='/images/oshaberu/音声合成-1.png' width={640} height={480} alt='音声合成-1' />
                </div>
                <div>
                  <Image src='/images/oshaberu/音声合成-2.png' width={640} height={480} alt='音声合成-2' />
                </div>
              </div>
            </div>
          </div>
        </main>

        <Footer />
      </div>
    </div>
  )
}

export default Home
