import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import YouTube from 'react-youtube';
import React from 'react';
import Header from '../../components/Header';
import Footer from '../../components/Footer';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Hitsuji Rere</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='max-w-screen-xl mx-auto'>
        <Header />

        <main>
          <div>
            <h1 className='text-3xl font-bold text-center p-6 typewriter'>
              シマエーる
            </h1>

            <div className="text-xl w-max mx-auto">
              <div className='space-y-6 whitespace-pre-wrap'>
                <p>学生向けコミュニケーションロボット</p>
                <p>高専プロコン2020にて発表</p>
                <p>本体 : Google AIY Voice Kit</p>
                <p>プログラム : Python</p>
                <p>音声認識 : Google Assistant API</p>
                <YouTube
                  videoId='kGZ-tcQfXwM'
                  opts={{
                    playerVars: {
                      start: 3600,
                    }
                  }}
                />
                <p>
                  <Link href='https://github.com/ishikawa-nct-iken/shimayell_aiy'>
                    <a className='border-b-2 hover:border-2 border-gray-100 border-b-black hover:border-black p-1 hover:p-2.5 duration-500'>GitHub</a>
                  </Link>
                </p>
              </div>
            </div>
          </div>
        </main>

        <Footer />
      </div>
    </div>
  )
}

export default Home
