import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import React from 'react';
import Header from '../components/Header';
import Footer from '../components/Footer';
import Details from '../components/Details';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='max-w-screen-xl mx-auto'>
        <Header />

        <main>
          {/* About */}
          <div className=''>
            <h2 id='about' className='text-3xl font-bold text-center p-6 typewriter'>
              About
            </h2>

            <div className="bg-black p-8 text-white text-xl w-max mx-auto my-6">
              <div className='space-y-6 whitespace-pre-wrap'>
                <p>const Name = {"'"}Hitsuji Rere{"'"};</p>
                <p>const なまえ = {"'"}ひつじ れれ{"'"};</p>
                <p>
                  const Twitter = {}
                  <Link href='https://twitter.com/HitsujiRere'>
                    <a className='underline'>@HitsujiRere</a>
                  </Link>
                </p>
                <p>
                  const GitHub = {}
                  <Link href='https://github.com/HitsujiRere'>
                    <a className='underline'>HitsujiRere</a>
                  </Link>
                </p>
              </div>
            </div>
          </div>

          {/* Skill */}
          <div className=''>
            <h2 id='skill' className='text-3xl font-bold text-center p-6'>
              Skill
            </h2>

            <div className="bg-black p-8 text-white text-xl w-max mx-auto my-6">
              <div className='space-y-6 whitespace-pre-wrap'>
                <Details
                  summaryOpen='const Languages = {'
                  summaryClose='const Languages = {...}'
                  className='space-y-6'
                  child={
                    <div className='space-y-6'>
                      <p>  Good: [</p>
                      <p>    C, C++, C#, JS, Python,</p>
                      <p>  ],</p>
                      <p>  HadUsed: [</p>
                      <p>    TS, Java,</p>
                      <p>  ],</p>
                      <p>  Leaning: [</p>
                      <p>    Rust, TS,</p>
                      <p>  ],</p>
                      <p>{'}'};</p>
                    </div>
                  }
                />
                <Details
                  open={true}
                  summaryOpen='const Skill = {'
                  summaryClose='const Skill = {...}'
                  className='space-y-6'
                  child={
                    <div className='space-y-6'>
                      <p>  CompetitiveProgramming: {'{'}</p>
                      <p>    Using: [ C++ ],</p>
                      <p>    AtCoder: {'{'}</p>
                      <p>      User: {}
                        <Link href='https://atcoder.jp/users/Deji'>
                          <a className='underline'>Deji</a>
                        </Link>
                        ,
                      </p>
                      <p>      HighestRate: 1455,</p>
                      <p>   {'}'},</p>
                      <p>  {'}'},</p>
                      <p>{'}'};</p>
                    </div>
                  }
                />
              </div>
            </div>
          </div>
        </main>

        <Footer />
      </div>
    </div>
  )
}

export default Home
