import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import React from 'react';
import Header from '../components/IndexHeader';
import Footer from '../components/Footer';
import Details from '../components/Details';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Hitsuji Rere</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='max-w-screen-xl mx-auto'>
        <Header />

        <main>
          {/* About */}
          <div>
            <h2 id='about' className='text-3xl font-bold text-center p-6 typewriter'>
              About
            </h2>

            <div className="bg-black p-8 text-white text-xl w-max mx-auto my-6">
              <div className='space-y-6 whitespace-pre-wrap'>
                <p>const Name = {"'"}Hitsuji Rere{"'"};</p>
                <p>const なまえ = {"'"}ひつじ れれ{"'"};</p>
                <p>
                  const Twitter = {}
                  <Link href='https://twitter.com/HitsujiRere'>
                    <a className='border-b-2 hover:border-2 border-black border-b-white hover:border-white p-1 hover:p-2.5 duration-500'>@HitsujiRere</a>
                  </Link>
                  ;
                </p>
                <p>
                  const GitHub = {}
                  <Link href='https://github.com/HitsujiRere'>
                    <a className='border-b-2 hover:border-2 border-black border-b-white hover:border-white p-1 hover:p-2.5 duration-500'>HitsujiRere</a>
                  </Link>
                  ;
                </p>
              </div>
            </div>
          </div>

          {/* Skill */}
          <div>
            <h2 id='skill' className='text-3xl font-bold text-center p-6'>
              Skill
            </h2>

            <div className="bg-black p-8 text-white text-xl w-max mx-auto my-6">
              <div className='space-y-6 whitespace-pre-wrap'>
                <Details
                  startOpen={true}
                  summaryOpen={<p>const Languages = &#123;</p>}
                  summaryClose={<p>const Languages = &#123;...&#125;</p>}
                  className='space-y-6'
                  child={
                    <div className='space-y-6'>
                      <p>  Good: [</p>
                      <p>    C, C++, C#, JS, Python,</p>
                      <p>  ],</p>
                      <p>  HadUsed: [</p>
                      <p>    TS, Java,</p>
                      <p>  ],</p>
                      <p>  Leaning: [</p>
                      <p>    Rust, TS,</p>
                      <p>  ],</p>
                      <p>{'}'};</p>
                    </div>
                  }
                />
                <Details
                  startOpen={true}
                  summaryOpen={<p>const Skill = &#123;</p>}
                  summaryClose={<p>const Skill = &#123;...&#125;</p>}
                  className='space-y-6'
                  child={
                    <div className='space-y-6'>
                      <p>  CompetitiveProgramming: {'{'}</p>
                      <p>    Using: [ C++ ],</p>
                      <p>    AtCoder: {'{'}</p>
                      <p>      User: {}
                        <Link href='https://atcoder.jp/users/Deji'>
                          <a className='border-b-2 hover:border-2 border-black border-b-white hover:border-white p-1 hover:p-2.5 duration-500'>Deji</a>
                        </Link>
                        ,
                      </p>
                      <p>      HighestRate: 1455,</p>
                      <p>    {'}'},</p>
                      <p>  {'}'},</p>
                      <p>{'}'};</p>
                    </div>
                  }
                />
              </div>
            </div>
          </div>

          {/* Awards */}
          <div>
            <h2 id='awards' className='text-3xl font-bold text-center p-6'>
              Awards
            </h2>

            <div className="bg-black p-8 text-white text-xl w-max mx-auto my-6">
              <div className='space-y-6 whitespace-pre-wrap'>
                <Details
                  startOpen={true}
                  summaryOpen={<p>const Award = &#123;</p>}
                  summaryClose={<p>const Award: &#123;...&#125;</p>}
                  className='space-y-6'
                  child={
                    <div className='space-y-6'>
                      <Details
                        startOpen={true}
                        summaryOpen={<p>  DCON2021: &#123;</p>}
                        summaryClose={<p>  DCON2021: &#123;...&#125;</p>}
                        className='space-y-6'
                        child={
                          <div className='space-y-6'>
                            <p>    Result: 7th,</p>
                            <p>    Product: <Link href='/products/oshaberu'>
                              <a className='border-b-2 hover:border-2 border-black border-b-white hover:border-white p-1 hover:p-2.5 duration-500'>おしゃべる</a>
                              </Link>,</p>
                            <p>  {'}'},</p>
                          </div>
                        }
                      />
                      <Details
                        startOpen={true}
                        summaryOpen={<p>  HIT2020: &#123;</p>}
                        summaryClose={<p>  HIT2020: &#123;...&#125;</p>}
                        className='space-y-6'
                        child={
                          <div className='space-y-6'>
                            <p>    Result: ICTまちづくり賞,</p>
                            <p>    Product: <Link href='/products/oshaberu'>
                              <a className='border-b-2 hover:border-2 border-black border-b-white hover:border-white p-1 hover:p-2.5 duration-500'>シマエーる</a>
                              </Link>,</p>
                            <p>  {'}'},</p>
                          </div>
                        }
                      />
                      <Details
                        startOpen={true}
                        summaryOpen={<p>  パソコン甲子園2020: &#123;</p>}
                        summaryClose={<p>  パソコン甲子園2020: &#123;...&#125;</p>}
                        className='space-y-6'
                        child={
                          <div className='space-y-6'>
                            <p>    Result: プログラミング部門本選出場,</p>
                            <p>  {'}'},</p>
                          </div>
                        }
                      />
                      <Details
                        startOpen={true}
                        summaryOpen={<p>  高専プロコン2020: &#123;</p>}
                        summaryClose={<p>  高専プロコン2020: &#123;...&#125;</p>}
                        className='space-y-6'
                        child={
                          <div className='space-y-6'>
                            <p>    Result: {'{'}</p>
                            <p>      自由部門: 特別賞,</p>
                            <p>      パテント審査部門: 奨励賞,</p>
                            <p>    {'}'},</p>
                            <p>  {'}'},</p>
                          </div>
                        }
                      />
                      <p>{'}'};</p>
                    </div>
                  }
                />
              </div>
            </div>
          </div>

          {/* Products */}
          <div>
            <h2 id='products' className='text-3xl font-bold text-center p-6'>
              Products
            </h2>

            <div className="bg-black p-8 text-white text-xl w-max mx-auto my-6">
              <div className='space-y-6 whitespace-pre-wrap'>
                <Details
                  startOpen={true}
                  summaryOpen={<p>const Products = &#123;</p>}
                  summaryClose={<p>const Products = &#123;...&#125;</p>}
                  className='space-y-6'
                  child={
                    <div className='space-y-6'>
                      <div className='border-l-4 hover:border-4 border-black border-l-white hover:border-white hover:py-2.5 duration-500'>
                        <Link href='/products/oshaberu'>
                          <a className='space-y-6'>
                            <p>  おしゃべる: [</p>
                            <p>    自由な声と喋れるスマートスピーカーの追加コンテンツ,</p>
                            <p>    DCON2021にて発表,</p>
                            <p>  ],</p>
                          </a>
                        </Link>
                      </div>
                      <div className='border-l-4 hover:border-4 border-black border-l-white hover:border-white hover:py-2.5 duration-500'>
                        <Link href='/products/twattaa'>
                          <a className='space-y-6'>
                            <p>  Twattaa: [</p>
                            <p>    授業の演習にて作成・発表した匿名掲示板,</p>
                            <p>  ],</p>
                          </a>
                        </Link>
                      </div>
                      <div className='border-l-4 hover:border-4 border-black border-l-white hover:border-white hover:py-2.5 duration-500'>
                        <Link href='/products/learn-processing'>
                          <a className='space-y-6'>
                            <p>  LearnProcessing: [</p>
                            <p>    部内用の発展的なProcessingの学習,</p>
                            <p>  ],</p>
                          </a>
                        </Link>
                      </div>
                      <div className='border-l-4 hover:border-4 border-black border-l-white hover:border-white hover:py-2.5 duration-500'>
                        <Link href='/products/fall-texts'>
                          <a className='space-y-6'>
                            <p>  FallTexts: [</p>
                            <p>    文字を落として、リアルタイムでみんなと共有,</p>
                            <p>  ],</p>
                          </a>
                        </Link>
                      </div>
                      <div className='border-l-4 hover:border-4 border-black border-l-white hover:border-white hover:py-2.5 duration-500'>
                        <Link href='/products/shimale'>
                          <a className='space-y-6'>
                            <p>  シマエーる: [</p>
                            <p>    学生向けコミュニケーションロボット,</p>
                            <p>    高専プロコン2020にて発表,</p>
                            <p>  ],</p>
                          </a>
                        </Link>
                      </div>
                      <div className='border-l-4 hover:border-4 border-black border-l-white hover:border-white hover:py-2.5 duration-500'>
                        <Link href='/products/shiritori-vs'>
                          <a className='space-y-6'>
                            <p>  しりとりVS: [</p>
                            <p>    1人で限界までしりとりしたり、CPUと対戦したり,</p>
                            <p>  ],</p>
                          </a>
                        </Link>
                      </div>
                      <div className='border-l-4 hover:border-4 border-black border-l-white hover:border-white hover:py-2.5 duration-500'>
                        <Link href='/products/hex-calcurator'>
                          <a className='space-y-6'>
                            <p>  HexCalcurator: [</p>
                            <p>    16進数で計算できる電卓,</p>
                            <p>  ],</p>
                          </a>
                        </Link>
                      </div>
                      <div className='border-l-4 hover:border-4 border-black border-l-white hover:border-white hover:py-2.5 duration-500'>
                        <Link href='/products/just10game'>
                          <a className='space-y-6'>
                            <p>  Just10Game: [</p>
                            <p>    数字で10を作る落ち物ゲーム</p>
                            <p>  ],</p>
                          </a>
                        </Link>
                      </div>
                      <div className='border-l-4 hover:border-4 border-black border-l-white hover:border-white hover:py-2.5 duration-500'>
                        <Link href='/products/yudetamago2'>
                          <a className='space-y-6'>
                            <p>  ゆでたまご２: [</p>
                            <p>    ゆでたまごを作るクリックアクションゲーム,</p>
                            <p>  ],</p>
                          </a>
                        </Link>
                      </div>
                      <p>{'}'};</p>
                    </div>
                  }
                />
              </div>
            </div>
          </div>

        </main>

        <Footer />
      </div>
    </div>
  )
}

export default Home
